name: build kernel

on:
  workflow_dispatch:

jobs:
  build-kernel:
    runs-on: ubuntu-20.04
    steps:
      - uses: manjaro-kernels/kernel-action@master
        with:
          gitlab-pw: ${{ secrets.gitlab_server_user }}
          bump-kernel: false
          bump-modules: false
          boxit-host: ${{ secrets.BOXIT_HOST }}
          boxit-target: ${{ secrets.BOXIT_TARGET }}
          ssh-key: ${{ secrets.SSH_PACKAGE_CI }}
